modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="Public Domain"
issueTrackerURL="https://github.com/Tfarcenim/Ferroustry/issues"
[[mods]] #mandatory
modId="ferroustry" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ferroustry" #mandatory
authors="Tfarecnim" #optional
description='''

Ore trees

'''